version: '3.4'

services:
  conexia.sr.webapi:
    image: songrecommendation
    build:
      context: .
      dockerfile: Conexia.SR.WebAPI\Dockerfile
    depends_on: 
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"